/**
 * 统一存放 action 常量
 */

// account.js
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const FETCH_VISITOR_SUCCESS = 'FETCH_VISITOR_SUCCESS';
export const FETCH_VISITOR_FAILED = 'FETCH_VISITOR_FAILED';

// course.js
export const COURSE_KNOWLEDGE_REQUEST = 'COURSE_KNOWLEDGE_REQUEST';
export const COURSE_KNOWLEDGE_SUCCESS = 'COURSE_KNOWLEDGE_SUCCESS';
export const COURSE_KNOWLEDGE_FAILURE = 'COURSE_KNOWLEDGE_FAILURE';
export const COURSE_COURSE_REQUEST = 'COURSE_COURSE_REQUEST';
export const COURSE_COURSE_SUCCESS = 'COURSE_COURSE_SUCCESS';
export const COURSE_COURSE_FAILURE = 'COURSE_COURSE_FAILURE';

export const SUBJECT_REQUEST = 'SUBJECT_REQUEST';
export const SUBJECT_SUCCESS = 'SUBJECT_SUCCESS';

export const UPLOAD_KNOWLEDGE_SUCCESS = 'UPLOAD_KNOWLEDGE_SUCCESS';
export const UPLOAD_COURSE_REQUEST = 'UPLOAD_COURSE_REQUEST';
export const UPLOAD_COURSE_SUCCESS = 'UPLOAD_COURSE_SUCCESS';
export const UPLOAD_COURSE_FAILURE = 'UPLOAD_COURSE_FAILURE';

// courseware.js
export const COURSEWARE_BLOCK_MOUSEDOWN = 'COURSEWARE_BLOCK_MOUSEDOWN';
export const COURSEWARE_SLIDE_MOUSEMOVE = 'COURSEWARE_SLIDE_MOUSEMOVE';
export const COURSEWARE_SLIDE_MOUSEUP = 'COURSEWARE_SLIDE_MOUSEUP';
export const COURSEWARE_SLIDE_MOUSEDOWN = 'COURSEWARE_SLIDE_MOUSEDOWN';
export const COURSEWARE_ADD_BLOCK = 'COURSEWARE_ADD_BLOCK';
export const COURSEWARE_DELETE_BLOCK = 'COURSEWARE_DELETE_BLOCK';
export const COURSEWARE_COPY_BLOCK = 'COURSEWARE_COPY_BLOCK';
export const COURSEWARE_OPTIONBTN_CLICK = 'COURSEWARE_OPTIONBTN_CLICK';
export const COURSEWARE_CROP_CANCEL = 'COURSEWARE_CROP_CANCEL';
export const COURSEWARE_CROP_COMPLETE = 'COURSEWARE_CROP_COMPLETE';
export const COURSEWARE_PASTE_BLOCK = 'COURSEWARE_PASTE_BLOCK';
export const COURSEWARE_ARROW_EVENT = 'COURSEWARE_ARROW_EVENT';
export const COURSEWARE_HEAD_CHANGETITLE = 'COURSEWARE_HEAD_CHANGETITLE'; // 改变课程名
export const COURSEWARE_LINK_EXCHANGE = 'COURSEWARE_LINK_EXCHANGE'; // 交换环节
export const COURSEWARE_LINK_ADD = 'COURSEWARE_LINK_ADD'; // 添加环节
export const COURSEWARE_LINK_DELETE = 'COURSEWARE_LINK_DELETE'; // 删除环节
export const COURSEWARE_SLIDE_MOVE_TO_LINK = 'COURSEWARE_SLIDE_MOVE_TO_LINK'; // 移动卡片到环节
export const COURSEWARE_SLIDE_MOVE = 'COURSEWARE_SLIDE_MOVE'; // 移动卡片
export const COURSEWARE_SLIDE_ADD = 'COURSEWARE_SLIDE_ADD'; // 添加卡片
export const COURSEWARE_SLIDE_DELETE = 'COURSEWARE_SLIDE_DELETE'; // 删除卡片
export const COURSEWARE_SLIDE_TO = 'COURSEWARE_SLIDE_TO'; // 滑动到卡片
export const COURSEWARE_SLIDE_REFRESH_THUMNAIL = 'COURSEWARE_SLIDE_REFRESH_THUMNAIL'; // 刷新卡片缩略图
export const COURSEWARE_EXERCISE_MERGE = 'COURSEWARE_EXERCISE_MERGE'; // 合并练习
export const COURSEWARE_EXERCISE_SPLIT = 'COURSEWARE_EXERCISE_SPLIT'; // 拆分练习
export const COURSEWARE_BLOCK_ACTIVATE = 'COURSEWARE_BLOCK_ACTIVATE'; // 激活块元素
export const COURSEWARE_EDIT_BLOCK = 'COURSEWARE_EDIT_BLOCK';
export const COURSEWARE_BLOCK_FOCUSED = 'COURSEWARE_BLOCK_FOCUSED';
export const COURSEWARE_TABLE_QUIKE_OPTION = 'COURSEWARE_TABLE_QUIKE_OPTION';
export const COURSEWARE_TABLE_RESIZE = 'COURSEWARE_TABLE_RESIZE';
export const COURSEWARE_QUESTION_SNAPSHOOT = 'COURSEWARE_QUESTION_SNAPSHOOT';
export const COURSEWARE_QUESTION_REDRAW = 'COURSEWARE_QUESTION_REDRAW';
export const COURSEWARE_SET_BLOCK_PROPS = 'COURSEWARE_SET_BLOCK_PROPS';
export const COURSEWARE_ZINDEX_UP = 'COURSEWARE_ZINDEX_UP';
export const COURSEWARE_ZINDEX_DOWN = 'COURSEWARE_ZINDEX_DOWN';
export const COURSEWARE_TABLE_CHANGE_ROW = 'COURSEWARE_TABLE_CHANGE_ROW';
export const COURSEWARE_TABLE_CHANGE_COLUMN = 'COURSEWARE_TABLE_CHANGE_COLUMN';
export const COURSEWARE_SLIDE_ADD_BACKGROUND = 'COURSEWARE_SLIDE_ADD_BACKGROUND';
export const COURSEWARE_SLIDE_REMOVE_BACKGROUND = 'COURSEWARE_SLIDE_REMOVE_BACKGROUND';
export const COURSEWARE_SLIDE_ADD_BACKGROUNDCOLOR = 'COURSEWARE_SLIDE_ADD_BACKGROUNDCOLOR';
export const COURSEWARE_SLIDE_REMOVE_BACKGROUNDCOLOR = 'COURSEWARE_SLIDE_REMOVE_BACKGROUNDCOLOR';
export const COURSEWARE_SHAPE_CHANGE_TYPE = 'COURSEWARE_SHAPE_CHANGE_TYPE';
export const COURSEWARE_GROUP_ALIGN = 'COURSEWARE_GROUP_ALIGN';
export const COURSEWARE_BLOCK_CHANGE_IMAGE = 'COURSEWARE_BLOCK_CHANGE_IMAGE';
export const COURSEWARE_TIMIMG_SAVEPPT = 'COURSEWARE_TIMIMG_SAVEPPT';
export const COURSEWARE_UNMOUNT_INITDATA = 'COURSEWARE_UNMOUNT_INITDATA';
export const COURSEWARE_CHANGE_ANIMATION_EFFECT = 'COURSEWARE_CHANGE_ANIMATION_EFFECT';
export const COURSEWARE_CHANGE_SLIDE_ANIMATION_EFFECT = 'COURSEWARE_CHANGE_SLIDE_ANIMATION_EFFECT';
export const COURSEWARE_CHANGE_SLIDE_ANIMATION_SPEED = 'COURSEWARE_CHANGE_SLIDE_ANIMATION_SPEED';
export const COURSEWARE_CHANGE_QUESTION_TYPE = 'COURSEWARE_CHANGE_QUESTION_TYPE';
export const COURSEWARE_CHANGE_SINGLE_ANSWER = 'COURSEWARE_CHANGE_SINGLE_ANSWER';
export const COURSEWARE_CHANGE_QUESTION_OPTIONS = 'COURSEWARE_CHANGE_QUESTION_OPTIONS';
export const COURSEWARE_MATCH_OPTIONS = 'COURSEWARE_MATCH_OPTIONS';
export const COURSEWARE_SAVE_TEXT_CONTENT = 'COURSEWARE_SAVE_TEXT_CONTENT';
export const COURSEWARE_SAVE_TABLE_CONTENT = 'COURSEWARE_SAVE_TABLE_CONTENT';
export const COURSEWARE_SELECT_BLOCKS = 'COURSEWARE_SELECT_BLOCKS';
export const COURSEWARE_TEXT_RESIZE = 'COURSEWARE_TEXT_RESIZE';
export const COURSEWARE_SAVE_TABLE_HTML = 'COURSEWARE_SAVE_TABLE_HTML';
export const COURSEWARE_CHANGE_SLIDE_INDEX = 'COURSEWARE_CHANGE_SLIDE_INDEX';
export const COURSEWARE_SAVE_QUESTION_CONTENT = 'COURSEWARE_SAVE_QUESTION_CONTENT';
export const COURSEWARE_SAVE_TABLE_CONTENT_AND_HTML = 'COURSEWARE_SAVE_TABLE_CONTENT_AND_HTML';
export const COURSEWARE_SELECT_ALL = 'COURSEWARE_SELECT_ALL';
export const COURSEWARE_EDITOR_ACTIVE = 'COURSEWARE_EDITOR_ACTIVE';
export const COURSEWARE_CHANGE_TEACHINGLINKING_TITLE = 'COURSEWARE_CHANGE_TEACHINGLINKING_TITLE';
export const COURSEWARE_COPY_TEACHINGLINK = 'COURSEWARE_COPY_TEACHINGLINK';
export const COURSEWARE_COPY_SLIDE = 'COURSEWARE_COPY_SLIDE';
export const COURSEWARE_IMAGE_LOADED = 'COURSEWARE_IMAGE_LOADED';
export const COURSEWARE_CHANGE_SUBJECT_ANSWER = 'COURSEWARE_CHANGE_SUBJECT_ANSWER';
export const COURSEWARE_CHANGE_WRAP_BLOCK = 'COURSEWARE_CHANGE_WRAP_BLOCK';
export const COURSEWARE_CONFIRM_QUESTION_OVERNUMBER = 'COURSEWARE_CONFIRM_QUESTION_OVERNUMBER';

// 首页-我的课件
export const COURSE_EDITOR_GET_DATA = 'COURSE_EDITOR_GET_DATA';
export const FETCHMYCOURSELIST_SUCCESS = 'FETCHMYCOURSELIST_SUCCESS';
export const UPDATE_SEARCH_LABEL = 'SAVE_SEARCH_VALUE';
export const UPDATE_FOLDER_LIST = 'SAVE_MY_FOLDER_DATA';
export const UPDATE_DOWNLOAD_MODAL = 'UPDATE_DOWNLOAD_MODAL';

// 首页-校本资源
export const FETCHSCHOOLCOURSELIST_SUCCESS = 'FETCHSCHOOLCOURSELIST_SUCCESS';

// 云基础平台
export const FETCHSCHOOLALLSUBJECT = 'FETCHSCHOOLALLSUBJECT';

export const HAMSTER = {
    BLOCK_ADD: 'BLOCK_ADD',
    BLOCK_ACTIVATE: 'BLOCK_ACTIVATE',
    BLOCK_PROPS_CHANGE: 'BLOCK_PROPS_CHANGE'
};
